export const Users = [
  { id: 1, profilePicture: '/assets/persons/1.jpg', username: 'John Doe-1' },
  { id: 2, profilePicture: '/assets/persons/2.jpg', username: 'John Doe-2' },
  { id: 3, profilePicture: '/assets/persons/3.jpg', username: 'John Doe-3' },
  { id: 4, profilePicture: '/assets/persons/4.jpg', username: 'John Doe-4' },
  { id: 5, profilePicture: '/assets/persons/5.jpg', username: 'John Doe-5' },
  { id: 6, profilePicture: '/assets/persons/6.jpg', username: 'John Doe-6' },
  { id: 7, profilePicture: '/assets/persons/7.jpg', username: 'John Doe-7' },
];

export const Posts = [
  {
    id: 1,
    desc: 'this is my first post in this facebook clone',
    photo: '/assets/posts/1.jpg',
    date: '19 mins ago',
    userId: 1,
    like: 56,
    comment: 12,
  },
  {
    id: 2,
    desc: 'this is my first post in this facebook clone',
    photo: '/assets/posts/2.jpg',
    date: '19 mins ago',
    userId: 2,
    like: 56,
    comment: 12,
  },
  {
    id: 3,
    desc: 'this is my first post in this facebook clone',
    photo: '/assets/posts/3.jpg',
    date: '19 mins ago',
    userId: 3,
    like: 56,
    comment: 12,
  },
  {
    id: 4,
    desc: 'this is my first post in this facebook clone',
    photo: '/assets/posts/4.jpg',
    date: '19 mins ago',
    userId: 4,
    like: 56,
    comment: 12,
  },
  {
    id: 5,
    desc: '',
    photo: '/assets/posts/5.jpg',
    date: '19 mins ago',
    userId: 5,
    like: 56,
    comment: 12,
  },
  {
    id: 6,
    desc: 'this is my first post in this facebook clone',
    photo: '/assets/posts/6.jpg',
    date: '19 mins ago',
    userId: 6,
    like: 56,
    comment: 12,
  },
  {
    id: 7,
    desc: '',
    photo: '/assets/posts/7.jpg',
    date: '19 mins ago',
    userId: 7,
    like: 56,
    comment: 12,
  },
  {
    id: 8,
    desc: 'this is my first post in this facebook clone',
    photo: '/assets/posts/8.jpg',
    date: '19 mins ago',
    userId: 7,
    like: 56,
    comment: 12,
  },
  {
    id: 9,
    desc: 'this is my first post in this facebook clone',
    photo: '/assets/posts/9.jpg',
    date: '19 mins ago',
    userId: 3,
    like: 56,
    comment: 12,
  },
  {
    id: 10,
    desc: '',
    photo: '/assets/posts/10.jpg',
    date: '19 mins ago',
    userId: 5,
    like: 56,
    comment: 12,
  },
];
